stages:
  - build

build:
  stage: build
  image: ubuntu:latest
  script:
    - git clone $CI_REPOSITORY_URL
    - cd $CI_PROJECT_NAME
    - apt-get update && apt-get install -y python3.9 python3-pip
    - python3.9 -m pip install --upgrade pip
    - pip install pytest
    - pytest